//
// Created by Strahinja on 5/9/2026.
//

#ifndef INC_2026_CYBERATTACK_DEBUGTOOLS_H
#define INC_2026_CYBERATTACK_DEBUGTOOLS_H

//AKO TREBA DA SE DODAJU NEKE STVARI TIPA PUNJENJE MUNICIJE NA NEKO DUGME DODAJTE TO OVDE
#define HITBOX_COLOR Color {255, 0, 127, 200}


#endif //INC_2026_CYBERATTACK_DEBUGTOOLS_H
