//
// Created by Strahinja on 5/7/2026.
//

#ifndef INC_2026_CYBERATTACK_ENTITYTYPES_H
#define INC_2026_CYBERATTACK_ENTITYTYPES_H
typedef enum {
    NONE,
    PLAYER,

    ENEMY_TURRET,
    ENEMY_MELEE_PLANE,
    ENEMY_RANGED_PLANE,
    BOSS,

    PLAYER_PROJECTILE,
    ENEMY_PROJECTILE,
    SPEED_POWERUP,
    AMMO_POWERUP,
    HEALTH_POWERUP
} EntityType;

#endif //INC_2026_CYBERATTACK_ENTITYTYPES_H
