//
// Created by Strahinja on 5/7/2026.
//

#ifndef INC_2026_CYBERATTACK_ENTITYTYPES_H
#define INC_2026_CYBERATTACK_ENTITYTYPES_H
typedef enum {
    PLAYER,
    ENEMY_TURRET,
    ENEMY_MELEE_PLANE,
    PLAYER_PROJECTILE,
    ENEMY_PROJECTILE
} EntityType;

#endif //INC_2026_CYBERATTACK_ENTITYTYPES_H
