#ifndef INC_2026_CYBERATTACK_SCREENS_H
#define INC_2026_CYBERATTACK_SCREENS_H

typedef enum{
    MAIN_MENU,
    LEVEL1,
    LEVEL2,
    LEVEL3,
    PAUSE_MENU,
    INFINITE_LEVEL,
    DEMO_MODE,
    SETTINGS
}SCREEN;



#endif //INC_2026_CYBERATTACK_SCREENS_H
