//
// Created by A1 on 5/10/2026.
//

#ifndef INC_2026_CYBERATTACK_STATES_H
#define INC_2026_CYBERATTACK_STATES_H
typedef enum {
    STRAIGHT_MOVEMENT,
    SINE_MOVEMENT,
    CIRCULAR_MOVEMENT,
}EnemyState;
#endif //INC_2026_CYBERATTACK_STATES_H
